[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
workspace-hack = { version = "0.1", path = "../workspace-hack" }

async-trait.workspace = true
thiserror.workspace = true
bon.workspace = true
uuid.workspace = true
time.workspace = true
serde.workspace = true